# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visualizer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, Ui_MainWindow):
        Ui_MainWindow.setObjectName("Ui_MainWindow")
        Ui_MainWindow.resize(760, 623)
        self.verticalLayoutWidget = QtWidgets.QWidget(Ui_MainWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 741, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.GraphLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.GraphLayout.setContentsMargins(0, 0, 0, 0)
        self.GraphLayout.setObjectName("GraphLayout")
        self.layoutWidget = QtWidgets.QWidget(Ui_MainWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 570, 741, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.cb_music_list = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.cb_music_list.sizePolicy().hasHeightForWidth())
        self.cb_music_list.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_music_list.setFont(font)
        self.cb_music_list.setObjectName("cb_music_list")
        self.horizontalLayout.addWidget(self.cb_music_list)
        self.pb_open_file_dir = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_open_file_dir.setFont(font)
        self.pb_open_file_dir.setObjectName("pb_open_file_dir")
        self.horizontalLayout.addWidget(self.pb_open_file_dir)
        self.layoutWidget1 = QtWidgets.QWidget(Ui_MainWindow)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 540, 741, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lb_current_loading_file = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lb_current_loading_file.sizePolicy().hasHeightForWidth())
        self.lb_current_loading_file.setSizePolicy(sizePolicy)
        self.lb_current_loading_file.setText("")
        self.lb_current_loading_file.setObjectName("lb_current_loading_file")
        self.horizontalLayout_2.addWidget(self.lb_current_loading_file)
        self.layoutWidget2 = QtWidgets.QWidget(Ui_MainWindow)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 500, 741, 42))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setSizeConstraint(
            QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed,
            QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.slide_time = QtWidgets.QSlider(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.slide_time.sizePolicy().hasHeightForWidth())
        self.slide_time.setSizePolicy(sizePolicy)
        self.slide_time.setMinimumSize(QtCore.QSize(525, 0))
        self.slide_time.setOrientation(QtCore.Qt.Horizontal)
        self.slide_time.setObjectName("slide_time")
        self.horizontalLayout_3.addWidget(self.slide_time)
        self.lb_current_time = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lb_current_time.sizePolicy().hasHeightForWidth())
        self.lb_current_time.setSizePolicy(sizePolicy)
        self.lb_current_time.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_current_time.setFont(font)
        self.lb_current_time.setText("")
        self.lb_current_time.setObjectName("lb_current_time")
        self.horizontalLayout_3.addWidget(self.lb_current_time)
        self.pb_stop_or_start = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pb_stop_or_start.sizePolicy().hasHeightForWidth())
        self.pb_stop_or_start.setSizePolicy(sizePolicy)
        self.pb_stop_or_start.setMinimumSize(QtCore.QSize(40, 40))
        self.pb_stop_or_start.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pb_stop_or_start.setText("")
        self.pb_stop_or_start.setObjectName("pb_stop_or_start")
        self.horizontalLayout_3.addWidget(self.pb_stop_or_start)

        self.retranslateUi(Ui_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Ui_MainWindow)

    def retranslateUi(self, Ui_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Ui_MainWindow.setWindowTitle(_translate("Ui_MainWindow", "Form"))
        self.label_2.setText(_translate("Ui_MainWindow", "播放列表："))
        self.pb_open_file_dir.setText(_translate("Ui_MainWindow", "打开文件目录"))
        self.label.setText(_translate("Ui_MainWindow", "当前播放："))
        self.label_3.setText(_translate("Ui_MainWindow", "时间轴："))
